# Generated by Django 4.1 on 2023-04-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Records",
            new_name="Record",
        ),
    ]
